version: '3.9'
services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: favlist
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis:7-alpine
        ports:
            - '6379:6379'
volumes:
    pgdata:
